development:
  adapter: postgresql
  encoding: utf8
  database: api_pie
  pool: 5
  username:
  password:

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: api_pie_test
  pool: 5
  username:
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: api_pie_production
  pool: 5
  username:
  password:
